DELETE http://localhost:3003/api/blogs/67abfdae2aba6406aff90f2e HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtuaWtvZ2hvIiwiaWQiOiI2N2E3NWUwMDNjNGQxNjQ5OTU0MDVkOTAiLCJpYXQiOjE3Mzk2MjIxOTQsImV4cCI6MTczOTYyNTc5NH0.a4Ozzhi1npfjreJ19Y85kHMqJrSMO2hYkUcHxFI38kQ
